name: Release Latest

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: release

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.bump-version.outputs.next }}
    steps:
      - uses: shabados/actions/setup-git-identity@release/v2
        with:
          user: Shabad OS Bot
          email: team@shabados.com
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_BOT_TOKEN }}
      - uses: shabados/actions/bump-version@release/v2
        id: bump-version
      - uses: shabados/actions/generate-changelog@release/v2
        # .tar to preserve permissions - https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: Create tar workspace archive to preserve file permissions
        run: tar -cvf /tmp/workspace.tar .
      - name: Upload workspace
        uses: actions/upload-artifact@v3
        with:
          name: release-workspace
          path: /tmp/workspace.tar

  publish-npm:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: release-workspace
        # .tar to preserve permissions - https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: Extract tar workspace archive to preserve file permissions
        run: tar -xvf workspace.tar
      - uses: shabados/actions/publish-npm@release/v2
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          npm_token: ${{ secrets.NPM_BOT_TOKEN }}

  publish-github:
    runs-on: ubuntu-20.04
    needs: prepare
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: release-workspace
        # .tar to preserve permissions - https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
      - name: Extract tar workspace archive to preserve file permissions
        run: tar -xvf workspace.tar
      - uses: shabados/actions/publish-github@release/v2
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}
          release_version: ${{ needs.prepare.outputs.release-version }}
